const data = [
    {
        id: 1,
        title: "Ecommerce Web Application",
        description: "I created this simple online store built using React utilizing the FakeStoreAPI to fetch product data examples to simulate the full functionality. I initially created this project with an outdated standard/version of React Router. Leading to have to restructure and update the components. The project demonstrates the use of React Hooks, state management, conditional rendering, and dynamic data fetching.",
        technologies: ["React", "React Router", "React Hooks", "FakeStoreAPI"],
        features: [
            'Browse products by category',
            'Search for products',
            'View product details',
            'Add products to cart',
            'Checkout submission'
        ],
        guide: "Getting started with create react app",
        host: "Local",
        repoLink: "https://github.com/HernandezA1007/INF655-MidtermProject",
        challenge: "The biggest challenge I faced was the restructuring of the components. I initially created this project with an outdated standard/version of React Router. Leading to have to restructure and update the components. I also had to learn how to use React Hooks to manage state and data fetching.",
        mainImage: 'https://via.placeholder.com/500',
        smallImage1: 'https://via.placeholder.com/250',
        smallImage2: 'https://via.placeholder.com/250',
    },

    // Add other projects here...
    {
        id: 2,
        title: 'Watchlist Web Application',
        description: 'This project focuses on using the Flask framework to create a watch list similar to one of my mini projects in INF 601 course: to do list application. The application allows the user to create and manage a movie list. By utilizing the Utelly API to search for movies and shows and adding them to their list. The user registers and has their own individual account to save their data. The purpose of the project is so the user has all their movies and shows in one place rather than multiple different streaming platforms and such apps. This project is still in development and will be updated in the future. ',
        technologies: ['Flask', 'Python', 'Utelly API', 'Bootstrap', 'SQLite3', 'HTML', 'CSS'],
        features: ['Incomplete', 'RapidAPI', 'Provides a list of template movies'],
        guide: 'Quickstart with Flask',
        host: 'Incomplete',
        repoLink: 'https://github.com/HernandezA1007/INF601-AHfinalproject',
        challenge: ' ',
        mainImage: 'https://via.placeholder.com/500',
        smallImage1: 'https://via.placeholder.com/250',
        smallImage2: 'https://via.placeholder.com/250',
    },
    {
        id: 3,
        title: 'Todo List Web Application',
        description: 'I created this simple web application that focuses on backend development. It allows users to create and manage tasks (add, remove, edit). The application is built using PHP and mySQL and ran via XAMAPP to host the application locally.',
        technologies: ['PHP', 'mySQL', 'XAMPP'],
        features: ['Add, Remove, and Edit', 'Stores tasks locally', 'Plan to implement user accounts'],
        guide: 'Guide for Project 3',
        host: 'Local',
        repoLink: 'https://github.com/HernandezA1007/INF653-ToDoListAssignment',
        challenge: ' ',
        mainImage: 'https://via.placeholder.com/500',
        smallImage1: 'https://via.placeholder.com/250',
        smallImage2: 'https://via.placeholder.com/250',
    },
    {
        id: 4,
        title: 'PHP Web Application',
        description: 'I built this application for a fake client "Zippy Used Autos", a car dealership. The application provides a homepage for the public viewing of the dealerships inventory with filter options. The admin or backend side allows users to view, add, edit, and delete vehicles. The application is built using PHP and mySQL and ran via XAMAPP to host the application locally. The application is still in development and will be updated in the future.',
        technologies: ['PHP', 'mySQL', 'XAMPP'],
        features: ['Public Homepage', 'Admin Backend', 'Both utilize responsive design'],
        guide: 'Guide for Project 4',
        host: 'Local',
        repoLink: 'https://github.com/HernandezA1007/INF653-MidtermProject',
        challenge: ' ',
        mainImage: 'https://via.placeholder.com/500',
        smallImage1: 'https://via.placeholder.com/250',
        smallImage2: 'https://via.placeholder.com/250',
    },
    {
        id: 5,
        title: 'PROJECT IDEA: React Native Mobile Application',
        description: 'I created this mobile application that focuses on frontend development. It allows users to create and manage tasks (add, remove, edit). The application is built using React Native and ran via Expo to host the application locally.',
        technologies: ['React Native', 'Expo'],
        features: ['Add, Remove, and Edit', 'Stores tasks locally', 'Plan to implement user accounts'],
        guide: 'Guide for Project 5',
        host: 'Local',
        repoLink: '#',
        challenge: ' ',
        mainImage: 'https://via.placeholder.com/500',
        smallImage1: 'https://via.placeholder.com/250',
        smallImage2: 'https://via.placeholder.com/250',
    },
    {
        id: 6,
        title: 'Ecommerce Web Application Extened',
        description: 'A continuation of the Ecommerce ReactJS Shopping Cart project. This project integrates Firebase to handle user authentication and data storage. I also implement CRUD operations...  ',
        technologies: ['React', 'React Router', 'React Hooks', 'Firebase', 'FakeStoreAPI', 'Bootstrap'],
        features: ['User Authentication', 'User Data Storage', 'CRUD Operations', 'Responsive Design'],
        guide: 'Getting started with create react app',
        host: 'Firebase/Incomplete',
        repoLink: 'https://github.com/HernandezA1007/INF655-Firebase-Auth-CRUD-Assignment',
        challenge: ' ',
        mainImage: 'https://via.placeholder.com/500',
        smallImage1: 'https://via.placeholder.com/250',
        smallImage2: 'https://via.placeholder.com/250',
    },
];

export default data;